wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717175087
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      - 62
      4: 3.9.19
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
