name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip=24.0
  - scikit-learn
  - matplotlib
  - plotly
  - pillow
  - mlflow
  - pip:
      - wandb
      - omegaconf